version: '3.7'
services: 

  rabbitmq-service:
    volumes:
      - './rabbitmq/rabbitmq-home:/var/lib/rabbitmq'
      # - './rabbitmq/rabbitmq-config:/etc/rabbitmq/'
      # - './rabbitmq/rabbitmq-db:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit'
    build: ./rabbitmq
    # expose:
    #   - "5672"
    ports:
      - 25672:15672
      - 5672:5672

  job-service:
    volumes:
      - './jobmanager:/usr/src/app'
    build: ./jobmanager
    expose:
      - "4545"
    ports:
      - 4545:4545
  
#  render-service:
#    image
#    volumes:
    
  frontend-service:
    volumes:
      - ./frontend:/home/node/app
    build: ./frontend
    
    ports:
      - 4646:3000
  
  file-service:
    volumes:
      - ./fileserver:/home/node/app
    build: ./fileserver
    ports:
      - 4441:4441

  render-service:
    volumes:
      - ./rendermock:/home/node/app
    build: ./rendermock
    expose:
      - "5672"